
-- FUNÇÕES DE AGREGRAÇÃO:
-- SUM(SOMA  DOS NUMEROS )
-- AVG ( CALCULA A MEDIA DOS VALORES)
-- MIN ( PEGA O MENOR NUMERO)
-- MAX ( PEGA O MUMERO MAIOR)

-- ----------------------- --

-- FUNCÇÕES DE CARACTERES: 

-- CONCAT -->Juntar nomes e sobrenomes sem separador específico, ou criar códigos únicos.
-- CONCAT_WS -- > JUNTA NOMES E SOBRENOMES COM SEPARADOR ESPECIFICO
-- CHAR_LENGTH  --> RETORNA A QTDE DE CARACTERES DE UMA STRING(TAMBEM CONTA OS ESPAÇO)
-- INSTR --> RETORNA A POSICÇÃO DA PARTE DA STRING PESQUISADA EM RELAÇÃO A SRING PRNCIPAL
-- LEFT --> RETORNA  OS CARACTERES DA ESQUERDA PARA DIREITA  CONFORME A QTD ESPECIFICADA
-- RIGTH --> RETORNA OS CARACTERES  DA STRING DA DIREITA PARA ESQUERDA CONFORME A QTD DOS CARACTERES ESPECIFICADA
-- GROUP BY SERVE PARA AGRUPAR  
-- HAVING  SERVE PARA  FILTRAR AS AGREGAÇÕES
-- LPAD --> COMPLETA O TAMANHO  INFORMADO TOTAL DA STRING COM CARACTERES A ESQUERDA
-- RPAD --> COMPLETA O TAMANHO INFORMADO TOTAL DA STRING COM CARACTERES A DIREITA
-- LTRIM --> REMOVE OS ESPAÇO EM BRANCO A ESQUERDA
-- RTRIM --> REMOVE ESPAÇO EM  BRANCO A DIREITA
-- TRIM --> REMOVE ESPAÇO EM BRANCO  EM AMBOS OS LADOS
-- SUBSTR --> EXTRAI PARTE DA STRING DE TAMANHO DETERMINADO MEDIANTE A UMA POSIÇÃO INICIAL
-- 	FORMAT --> FORMATA VALOR MONETARIO PARA O FORMATO BRASILEIRO
-- REVERSE --> APRESENTA A STRING EM ORDEM REVERSA
-- REPEAT --> REPETE STRING MEDIANTE  A QUANTIDADE DE VEZES DETERMINADA
-- REPLACE --> SUBSTITUI AS STRING  DESEJADA 
-- UPPER -->  CONVERTE DE MINUSCULO PARA MAIUSCULO
-- LOWER -->  CONVERTE MAIUSCULO PARA 

-- ------------------------------ -- 

-- FUNÇÕES DE DATAS
-- DATE_ ADD -->  ADD UMA DATA MEDIANTE DE UM INTERVALO(DIA[DAY], MESES[MONYH], ANO[YEAR]
-- CURDATE() -->  RETORNAR A  DATA ATUAL 
-- DATE_SUB() --> SUBTRAI DATAS MEDIANTE DE UM INTERVALO(DIA[DAY], MESES[MONYH], ANO[YEAR]
-- DAY/ MONTH / YEAR --> RETORNA A DATA SEPARADA
-- DATEDIFF --> RETORNA A DIFERENÇA (EM DIAS) ENTRE DUAS DATAS
-- DAYOFFWEEK -->   TRAS O DIA DA SEMENA DE 1 A 7
-- DAYOFFMONTH --> TRAS O MES DE 1 A 12
-- DAYOFYEAR -->  TRAS O DIA DO ANO  
-- MONTHNAME --> RETORNA O NOME DO MÊS
-- DAYNAME --> RETORNA O NOME DO DIA
-- NOW() --> RETORNA A DATA E A HORA
 -- LAST DAY RETORNA O ÚLTIMO DIA DO MÊS 
SELECT 
	cand_nome as "CANDIDATO",
    cand_numero as "NUMERO"
FROM candidato
where cand_foto is null;


-- count
SELECT 
	COUNT(*) AS" QDT_FOTO_NULA"
FROM candidato
where cand_foto is  NOT null;

SELECT 
	COUNT(*) AS" QDT_FOTO_NULA"
FROM candidato
where cand_foto is null;

select 
COUNT(*)  AS "QTD_CANDIDATOS",
	sum(cand_numero) as "NUMERO",
    AVG(cand_numero) as "MÈDIA",
    min(cand_numero) as "Menor Num",
    max(cand_numero) as "Maior Num"
from candidato;

--  HAVING  SERVE PARA  FILTRAR AS AGREGAÇÕES
SELECT 
part_numero  as"Partido",
count(*) as "QTD_CANDIDATOS"
FROM candidato
WHERE cand_nome like "%A"
group  by part_numero
having COUNT(*) > 2;

select 
	count(*) AS "QTD_VOTOS",
    cand_numero  as "numero do candidato"
from voto
group  by cand_numero
having  count(*) = 2;

-- EX CHAR_LENGTH

SELECT CHAR_LENGTH("INSTITUTO FEDERAL") AS "CHAR_LENGTH";

--  EX INSTR 
SELECT INSTR("INSTITUTO FEDERAL", "i") AS   "INSTR";

-- EX LEF / RIGHT

SELECT LEFT("INSTITUTO FEDERAL",9) AS   "INSTR";

-- EX LPAD / RPAD
-- IMPLEMENTAS OS @  NA PARTE ESQUERDA
SELECT LPAD("IFRO",15,"@") AS "LPAD";
-- IMPLEMTA os @ na parte direita
SELECT RPAD("IFRO",10,"@") AS "RPAD"; 

-- EX LTRIM / RTRIM / TRIM
SELECT LTRIM("   IFRO") AS "LTRIM";

SELECT RTRIM("IFRO  ") AS "RTRIM";

SELECT TRIM("  IFRO  ") AS "TRIM";

-- EX SUBSTR 

SELECT substr("CASSIO SOUZA", 8,3) AS "SUBSTR";


--  EX REVERSE 

SELECT REVERSE("YAG O") AS "REVERSE";

-- EX REPEAT 
SELECT REPEAT("JOJO REFERENCES???? |||", 11) AS "REPEAT";

-- FORMAT
SELECT format(1234.567, 2, 'de_DE') as "FORMAT";


--  EX REPLACE
 SELECT REPLACE("RAYRE LÚISY" ,"LÚISY", "JUBILEU") AS "REPLACE";
 
 -- EX UPPER / LOWER 
 
 SELECT UPPER("os d ta baforando lança no piru de marginal") as "UPPER";
 
 SELECT LOWER("DOUTOR ME EXPLICA PORQUE É QUE AS VEZES QUANDO EU FICO PARADO  SEM FZR ND O MEU PAU FICA DURO") AS "LOWER";
 
 -- DATE_ADD
	SELECT DATE_ADD("2026-04-13", INTERVAL 150 DAY) AS "INTERVALO_DIA",
		DATE_ADD("2026-04-13", INTERVAL 15  MONTH)AS "INTERVALO_DIA",
        DATE_ADD("2026-04-13", INTERVAL 15  YEAR )AS "INTERVALO_DIA";

-- CURDATE
	SELECT CURDATE() AS "DATA ATUAL";
    
-- DATA_SUB
	SELECT DATE_SUB(CURDATE(), INTERVAL 15  DAY)AS "INTERVALO_DIA",
			DATE_SUB(CURDATE(), INTERVAL 15  MONTH)AS "INTERVALO_DIA",
        	DATE_SUB(CURDATE(), INTERVAL 15  YEAR)AS "INTERVALO_DIA";
            
-- DAY/ MONTH / YEAR
SELECT CURDATE() as "DATA ATUAL",
DAY(CURDATE()) AS  "DIA",
MONTH(CURDATE())AS "MÊS",
YEAR(CURDATE()) AS "ANO";

-- DATEDIFF
SELECT DATEDIFF(CURDATE(),"2008-07-24") / 365 AS "DIFERENÇA EM DIAS";

-- DAYOFWEEK 
SELECT DAYOFWEEK("2008-07-24") AS "DIA DA SEMANA";

-- DAYOFMONTH
SELECT DAYOFMONTH("2008-07-24") AS "DIA DO MÊS";

-- DAYOFYEAR 
SELECT DAYOFYEAR(CURDATE()) AS "DIA DO ANO";

-- MONTHNAME 
SELECT MONTHNAME(CURDATE()) AS "NOME_MÊS";

-- DAYNOME
SELECT DAYNAME(CURDATE()) AS "NOME_DIA";

-- NOW() 
 SELECT NOW() AS "DATA E HORA";
 
 -- LAST DAY
 -- RETORNA O ÚLTIMO DIA DO MÊS 
 SELECT LAST_DAY(CURDATE()) AS "ULTIMO DO MÊS";
 
 
 -- DATE_FORMAT
SELECT CURDATE() AS "DATA ATUAL",
DATE_FORMAT(CURDATE(), '%d/%m/%y') as "DATA ATUAL FORMATADA",
	now() as "DATA HORA ATUAL",
    DATE_FORMAT(NOW(), '%d/%m/%y %H:%i:%S')  AS "DATA/HORA ATUAL FORMATADA";-- se deixa  o y minusculo ele abrevia o ano